import { toTitleCase } from "./helpers";

export const quillSettings = {
  modules: {
    toolbar: [
      [{ size: ["small", false, "large", "huge"] }],
      ["bold", "italic", "underline"],
      [
        { list: "ordered" },
        { list: "bullet" },
        { indent: "-1" },
        { indent: "+1" },
      ],
      [{ align: ["", "center", "right", "justify"] }],
      ["link"],
    ],
  },
  formats: ["bold"],
};

const CATEGORIES = [
  "accounting",
  "advertising",
  "agriculture",
  "anatomy",
  "anthropology",
  "archaeology",
  "architecture",
  "art/design",
  "astronomy",
  "aviation",
  "bartending",
  "bible studies",
  "biochemistry",
  "biology",
  "business",
  "chemistry",
  "classics",
  "computer networking",
  "computer science",
  "criminology",
  "dance",
  "dentistry",
  "economics",
  "engineering",
  "finance",
  "fitness",
  "games",
  "gardening",
  "general vocab",
  "geography",
  "geology",
  "grammar",
  "health care",
  "history",
  "immunology",
  "insurance",
  "internet",
  "journalism",
  "language",
  "law",
  "literature",
  "management",
  "mathematics",
  "medical",
  "meteorology",
  "microbiology",
  "military",
  "music",
  "new media",
  "nursing",
  "nutrition",
  "organic chemistry",
  "pathology",
  "pharmacology",
  "philosophy",
  "physics",
  "physiology",
  "plant sciences",
  "political studies",
  "psychology",
  "real estate & planning",
  "religious studies",
  "science",
  "social studies",
  "sociology",
  "software",
  "speech language pathology",
  "sports",
  "travel",
  "veterinary medicine",
  "writing",
  "zoology",
  "other",
];

export const categories = CATEGORIES.map((cat) => {
  return {
    label: toTitleCase(cat),
    value: cat,
  };
});
